name: release
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-rc*"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.TAG_PUSH_TOKEN }}
      - name: Add targets
        run: |
          rustup target add x86_64-unknown-linux-gnu x86_64-apple-darwin x86_64-pc-windows-gnu
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Install shippo
        run: cargo install --path crates/shippo
      - name: Clean (avoid host/container artifact reuse)
        run: cargo clean
      - name: Build & package
        run: shippo --config .shippo.toml package
      - name: Release
        env:
          CARGO_TARGET_DIR: target-cross
          GITHUB_TOKEN: ${{ secrets.TAG_PUSH_TOKEN }}
        run: shippo --config .shippo.toml release
